### ISSUE TITLE
Exception found when create notification, Chrome 44.0.2403.133 on Android 4.4.2

### ISSUE THREAD

**Issue by leosuncin** [ttsvetko/HTML5-Desktop-Notifications#27]
Request notification permission works fine, but when try to show notification not work. 
Error stack: 
```
TypeError: Failed to construct 'Notification': Illegal constructor. Use ServiceWorkerRegistration.showNotification() instead.
    at TypeError (native)
    at getNotification (http://localhost/vendor/html5-notifications/desktop-notify.js:72:29)
    at Object.createNotification (http://localhost/vendor/html5-notifications/desktop-notify.js:177:28)
```
Works fine in Firefox 40.0 in the same Android OS

**Comment by EpokK** [comment]
+1

**Comment by ttsvetko** [comment]
Current polyfill does not support notifications within ServiceWorkers, yet. Will implement that soon.
